apiVersion: apps/v1
kind: Deployment
metadata:
  name: meteo-deployment
spec:
  selector:
    matchLabels:
      app: meteo
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: meteo
    spec:
      containers:
        - name: meteo
          imagePullPolicy: Always
          image: ilysokon/meteo:latest
          ports:
            - containerPort: 8080