name: Dependency Snapshot

on:
  push:
    branches:
      - main



jobs:
  snapshot:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Submit dependency snapshot
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d @dependencies.json \
          https://api.github.com/repos/${{ github.repository }}/dependency-graph/snapshots
